In [2]:
# installing libraries
!pip install Kaggle

Requirement already satisfied: Kaggle in c:\users\rajat\anaconda3\lib\site-packages (1.7.4.2)
Requirement already satisfied: webencodings in c:\users\rajat\anaconda3\lib\site-packages (from Kaggle) (0.5.1)
Requirement already satisfied: certifi>=14.05.14 in c:\users\rajat\anaconda3\lib\site-packages (from Kaggle) (2022.12.7)
Requirement already satisfied: requests in c:\users\rajat\anaconda3\lib\site-packages (from Kaggle) (2.28.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\rajat\anaconda3\lib\site-packages (from Kaggle) (1.26.14)
Requirement already satisfied: protobuf in c:\users\rajat\anaconda3\lib\site-packages (from Kaggle) (6.30.2)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\rajat\anaconda3\lib\site-packages (from Kaggle) (65.6.3)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\rajat\anaconda3\lib\site-packages (from Kaggle) (2.8.2)
Requirement already satisfied: six>=1.10 in c:\users\rajat\anaconda3\lib\site-packages (from Kaggle) (1.16.0)
Requirement already satisfied: charset-normalizer in c:\users\rajat\anaconda3\lib\site-packages (from Kaggle) (2.0.4)
Requirement already satisfied: python-slugify in c:\users\rajat\anaconda3\lib\site-packages (from Kaggle) (5.0.2)
Requirement already satisfied: tqdm in c:\users\rajat\anaconda3\lib\site-packages (from Kaggle) (4.64.1)
Requirement already satisfied: idna in c:\users\rajat\anaconda3\lib\site-packages (from Kaggle) (3.4)
Requirement already satisfied: bleach in c:\users\rajat\anaconda3\lib\site-packages (from Kaggle) (4.1.0)
Requirement already satisfied: text-unidecode in c:\users\rajat\anaconda3\lib\site-packages (from Kaggle) (1.3)
Requirement already satisfied: packaging in c:\users\rajat\anaconda3\lib\site-packages (from bleach->Kaggle) (22.0)
Requirement already satisfied: colorama in c:\users\rajat\anaconda3\lib\site-packages (from tqdm->Kaggle) (0.4.6)

In [4]:
# importing the libraries
import kaggle

In [5]:
# downloading the dataset using kaggle api
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv --force

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv to C:\Users\rajat\Documents\Data Analytics Projects

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<?, ?B/s]

In [6]:
## extracting file from zipfile (if required)
import zipfile
zip_ref = zipfile.ZipFile('orders.csv.zip')
zip_ref.extractall()  # extract file to directory
zip_ref.close()  # to close the file

In [11]:
# Read data from file and handle Null values
# !pip install pandas
# import pandas as pd
df = pd.read_csv('orders.csv', na_values= ['Not Available', 'unknown'])
df.head(20)
# df['Ship Mode'].unique()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,NaN,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,NaN,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [12]:
# Rename column names ..convert into lower case and replace space into underscore
# df.rename(columns={'Order Id':'order_id', 'City':'city'}, inplace='true')
df.columns= df.columns.str.lower()
df.columns= df.columns.str.replace(' ','_')
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [13]:
# Derive new columns discount, sales_price and profit
df['discount']= df['list_price'] * df['discount_percent'] * 0.01
df['sales_price']= df['list_price'] - df['discount']
df['profit']= df['sales_price'] - df['cost_price']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sales_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [15]:
# Convert order_date from object data type to datetime
df['order_date']=pd.to_datetime(df['order_date'], format="%Y-%m-%d")
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sales_price                float64
profit                     float64
dtype: object

In [18]:
# Drop cost_price, list_price and discount_percent
df.drop(columns= ['cost_price','list_price','discount_percent'], inplace=True)
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sales_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [19]:
# Save the Transformed DataFrame as a CSV File
df.to_csv('transformed_data.csv', index=False)

In [21]:
# Load data into SQL Server by creating new database Sales not under master database
import sqlalchemy as sal
from sqlalchemy import text

In [22]:
# Create an engine connected to the master database
engine = sal.create_engine('mssql://Rajat\\SQLEXPRESS/master?driver=ODBC+DRIVER+17+FOR+SQL+SERVER')
conn = engine.connect().execution_options(isolation_level="AUTOCOMMIT")

# Create the Sales database if it does not exist
conn.execute(text("""
    IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'Sales')
    BEGIN
        CREATE DATABASE Sales
    END
"""))

# Close the connection to master
conn.close()

In [23]:
# Now connect to the new 'Sales' database
engine = sal.create_engine('mssql://Rajat\\SQLEXPRESS/Sales?driver=ODBC+DRIVER+17+FOR+SQL+SERVER')
conn = engine.connect()
print("Connected to the Sales database!")

#Explanation:
#execution_options(isolation_level="AUTOCOMMIT"): This is needed because CREATE DATABASE cannot be inside a transaction.

#The query now uses BEGIN...END to properly handle conditional creation.

# We then close the connection to master and reconnect to Sales.

Connected to the Sales database!

In [24]:
# Load the data into sql server using append function

df.to_sql('orders', con=conn, index=False, if_exists='replace')

-1